services:
  - type: web
    name: new-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AWSS3_BUCKET
        sync: false
      - key: AWSREGION
        sync: false
      - key: AWSACCESS_KEY_ID
        sync: false
      - key: AWSSECRET_ACCESS_KEY
        sync: false
